version: '3.7'

services:
  mlapi1:
    image: mlapi:latest
    restart: on-failure
    volumes:
      - ./config.ini:/app/config.ini
    ports:
      - "8001:8000"

  mlapi2:
    image: mlapi:latest
    restart: on-failure
    ports:
      - "8002:8000"

  gateway:
    image: nginx
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    command: 
      - bash
      - -c
      - nginx -g 'daemon off;'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mlapi1
      - mlapi2
      